"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['whistui.py']
DATA_FILES = ['cards', 'Info.plist', 'icon.icns']
OPTIONS = {'argv_emulation': False,
           'plist': 'Info.plist'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
